name: Reminder

on:
  schedule:
  - cron: "0 16 * * 1-5"

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout master
      run: git checkout master
    - name: Install jq
      run: |
          sudo apt-get update
          sudo apt-get install jq
    - name: Remind everyone
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
          ./reminder.sh $TOKEN G019Z66BFFS
          ./reminder.sh $TOKEN G0199H7UPD1
          ./reminder.sh $TOKEN G019Z6HGZ24
          ./reminder.sh $TOKEN G0199BFQURG
          ./reminder.sh $TOKEN G0199BM6D98
          ./reminder.sh $TOKEN G019MVCUZS5
          ./reminder.sh $TOKEN G019N02A0QZ
          ./reminder.sh $TOKEN G0192KMCKP0
          ./reminder.sh $TOKEN G01980ENUF7
          ./reminder.sh $TOKEN G01980QMV1B
          ./reminder.sh $TOKEN G0199HKA4Q3
          ./reminder.sh $TOKEN G019N0K4YNM
          ./reminder.sh $TOKEN G0199GX0TD1
          ./reminder.sh $TOKEN G0192JV5CQN
          ./reminder.sh $TOKEN G018UKAFYCX
          ./reminder.sh $TOKEN G019FH8PG12
